[general]
import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml",
    "~/.config/alacritty/keybindings.toml"
]

[terminal.shell]
args = ['--login']
program = "/opt/homebrew/bin/fish"

[window]
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.7
blur = true
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 18
